systemLog:
  destination: file
  path: /ncf/gershman/Lab/scripts/VGDL/mongodb/mongo.log
  logAppend: true
storage:
  dbPath: /ncf/gershman/Lab/scripts/VGDL/mongodb
#net:
#  bindIp: 127.0.0.1   <---- commented out to allow connections from other nodes on NCF TODO more secure way; but if we use IP, might change => kill progress
