bootstrap: docker
from: python:2

%files
  # move project requirements inside the container
  requirements.txt /requirements.txt

%post
  # install pip packages
  pip install --trusted-host pypi.python.org -r /requirements.txt
