
## Planner hyperparameters
hyperparameter_sets = [
    {'idx'           : 0,
     'short_horizon' : False,
     'first_order_horizon': True,
     'sprite_first_alpha': 10000,
     'sprite_second_alpha': 100,
     'sprite_negative_mult': .1,
     'multisprite_first_alpha': 10000,
     'multisprite_second_alpha': 100,
     'novelty_first_alpha': 5000,
     'novelty_second_alpha': 50,
     },
    {'idx'           : 1,
     'short_horizon' : False,
     'first_order_horizon': False,
     'sprite_first_alpha': 10000,
     'sprite_second_alpha': 100,
     'sprite_negative_mult': 10.,
     'multisprite_first_alpha': 10000,
     'multisprite_second_alpha': 100,
     'novelty_first_alpha': 5000,
     'novelty_second_alpha': 50,
     },
    {'idx'           : 2,
     'short_horizon' : False,
     'first_order_horizon': False,
     'sprite_first_alpha': 10000,
     'sprite_second_alpha': 100,
     'sprite_negative_mult': .1,
     'multisprite_first_alpha': 10000,
     'multisprite_second_alpha': 100,
     'novelty_first_alpha': 5000,
     'novelty_second_alpha': 50,
     },
    {'idx'           : 3,
     'short_horizon' : True,
     'first_order_horizon': True,
     'sprite_first_alpha': 10000,
     'sprite_second_alpha': 100,
     'sprite_negative_mult': 10, #normally .1
     'multisprite_first_alpha': 10000,
     'multisprite_second_alpha': 100,
     'novelty_first_alpha': 5000,
     'novelty_second_alpha': 50,
     },
    {'idx'           : 4,
     'short_horizon' : True,
     'first_order_horizon': True,
     'sprite_first_alpha': 10000,
     'sprite_second_alpha': 100,
     'sprite_negative_mult': .1, #normally .1
     'multisprite_first_alpha': 10000,
     'multisprite_second_alpha': 100,
     'novelty_first_alpha': 5000,
     'novelty_second_alpha': 10,
     }
]



## Metacontroller params:
metacontroller_sets = [
    ## Original
    {'idx': 0,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'conservative_max_nodes': 50,
    'extra_atom': False,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 200,
    'objectLocationTrackingLimit': 8,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },
    ## Simplifying: removing objectnumbertrackinglimit, objectLocationTrackingLimit, extraAtom always on
    {'idx': 1,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'conservative_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 10000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'conservative_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },

    {'idx': 3,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [400,1000,2000],
    'conservative_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },

    {'idx': 4,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [40,250,500],
    'conservative_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },

    {'idx': 5,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 10000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [400,1000,2000],
    'conservative_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },

    {'idx': 6,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'conservative_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 10
    },

    {'idx': 7,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 10000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'conservative_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 10
    },

    {'idx': 8,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'conservative_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 220,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },

    {'idx': 9,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 10000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'conservative_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 220,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },
    {'idx': 10,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 10000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'conservative_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 220,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 10
    }
]
