
## Planner hyperparameters
hyperparameter_sets = {
    'short-term':{'idx'           : 'short-term',
     'short_horizon' : True,
     'return_subgoal_plans': True,
     'sprite_first_alpha': 10000,
     'sprite_second_alpha': 100,
     'sprite_negative_mult': .1, #normally .1
     'multisprite_first_alpha': 10000,
     'multisprite_second_alpha': 100,
     'novelty_first_alpha': 5000,
     'novelty_second_alpha': 50,
     },
     'long-term':{'idx'           : 'long-term',
     'short_horizon' : False,
     'return_subgoal_plans': False,
     'sprite_first_alpha': 10000,
     'sprite_second_alpha': 100,
     'sprite_negative_mult': 10.,
     'multisprite_first_alpha': 10000,
     'multisprite_second_alpha': 100,
     'novelty_first_alpha': 5000,
     'novelty_second_alpha': 50,
     }
}


## Metacontroller params:
metacontroller_sets = [
    ## Normal, simplified: removing objectnumbertrackinglimit, objectLocationTrackingLimit, extraAtom always on
    {'idx': 1,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },
    ### AGH lesions ###
    # boltzmann ablation
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    # hyps specific to boltzmann ablation
    'bfs_depth': 3,
    'bfs_range': 0,
    'boltz_init': 8.0,
    'boltz_min': 0.1,
    'boltz_exploit': 10000,
    'epsilon_init' : 1.0,
    'epsilon_min' : 0.1,
    'epsilon_exploit' : 10000,
    'win_bonus': 1000000
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'planner_lesion': 'IW-AGH3'
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'planner_lesion': 'AGH1'
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'planner_lesion': 'AGH2'
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'planner_lesion': 'AGH3'
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'planner_lesion': 'IW'
    },
    ### Hypothesis-space lesions ###
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'dynamic_type_lesion': ['Chaser']
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'dynamic_type_lesion': ['Missile']
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'dynamic_type_lesion': ['speed']
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'interaction_lesion': ['bounceForward'],
    'interaction_lesion_replacement': 'nothing',
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'interaction_lesion': ['pullWithIt'],
    'interaction_lesion_replacement': 'nothing',
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'interaction_lesion': ['killSprite'],
    'interaction_lesion_replacement': 'nothing',
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'interaction_lesion': ['cloneSprite'],
    'interaction_lesion_replacement': 'nothing',
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'interaction_lesion': ['transformTo'],
    'interaction_lesion_replacement': 'nothing',
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2,
    'interaction_lesion': ['teleportToExit'],
    'interaction_lesion_replacement': 'nothing',
    },
    ## Normal, simplified: removing objectnumbertrackinglimit, objectLocationTrackingLimit, extraAtom always on
    {'idx': 1,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },
    ## End of planner lesions ##
    {'idx': 1,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },
    ## Original
    {'idx': 0,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': False,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 200,
    'objectLocationTrackingLimit': 8,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },
    ## Simplifying: removing objectnumbertrackinglimit, objectLocationTrackingLimit, extraAtom always on
    {'idx': 1,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },
    {'idx': 2,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 10000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },

    {'idx': 3,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [400,1000,2000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },

    ## KEEP
    {'idx': 4,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [40,250,500],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },

    {'idx': 5,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 10000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [400,1000,2000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },

    ##KEEP
    {'idx': 6,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 10
    },
    ##KEEP
    {'idx': 7,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 10000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 55,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 10
    },

    {'idx': 8,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 1000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 220,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },

    {'idx': 9,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 10000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 220,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 2
    },
    {'idx': 10,
    'random_steps_on_plan_failure': 5,
    'longHorizonNodes': 10000,
    'longhorizonAnnealing': 2.,
    'shortHorizonRandomChoice': [200,500,1000],
    'stall_mode_max_nodes': 50,
    'extra_atom': True,
    'noNewObjectNum': 220,
    'objectNumberTrackingLimit': 1000,
    'objectLocationTrackingLimit': 1000,
    'safeDistance': 3,
    'longHorizonObservationLimit': 10
    }
]
